services:
  db:
    container_name: spring-boot-db
    image: "postgres:latest"

    ports:
      - 5332:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JALENlewis2023!$
      POSTGRES_DB: project_db
