spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/project-db
spring.datasource.username=postgres
spring.datasource.password=JALENlewis2023!$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=your_jwt_secret_key
jwt.expiration=3600000