spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/project-db
spring.datasource.username=postgres
spring.datasource.password=JALENlewis2023!$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.ai.google.genai.api-key=AIzaSyCqA5D1i7sVYDsK65wpV2GlneS2GtVJkYc
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

google.maps.api.key=AIzaSyAMhbjwPG1IGqCB1Siu_Pxt4W1--9Jy7NE

jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long-here
jwt.expiration=3600000