spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/project-db
spring.datasource.username=postgres
spring.datasource.password=JALENlewis2023!$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.format_sql=true
spring.jpa.show-sql=true